# Generated by Django 5.1.7 on 2025-04-03 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_characteristic_product_characteristic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='ref',
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.catagory'),
        ),
    ]
