# Generated by Django 5.1.7 on 2025-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_catagory_options_remove_product_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
