# Generated by Django 5.1.7 on 2025-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_catagory_remove_product_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(max_length=255),
        ),
    ]
