# Generated by Django 5.1.7 on 2025-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_catagory_characteristic_alter_product_catagory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristic',
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
