# Generated by Django 5.1.7 on 2025-04-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_characteristic_alter_product_catagory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'Catagory', 'verbose_name_plural': 'Catagories'},
        ),
    ]
