# Generated by Django 5.1.7 on 2025-04-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.ManyToManyField(to='api.characteristic'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='title',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
