# Generated by Django 5.1.7 on 2025-04-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_characteristic_alter_characteristic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
