# Generated by Django 5.1.7 on 2025-04-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_characteristic_title_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.ManyToManyField(blank=True, to='api.characteristic'),
        ),
    ]
