# Generated by Django 5.1.7 on 2025-04-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_characteristic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
